# Generated by Django 4.2.24 on 2025-11-03 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleResidente',
            fields=[
                ('id_detalle_residente', models.AutoField(primary_key=True, serialize=False)),
                ('propietario', models.BooleanField(default=True)),
                ('apartamento', models.IntegerField()),
                ('torre', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_residente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('id_parqueadero', models.IntegerField(db_column='id_parqueadero', primary_key=True, serialize=False)),
                ('numero_parqueadero', models.CharField(max_length=6)),
                ('comunal', models.BooleanField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'parqueadero',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id_sorteo', models.AutoField(db_column='id_sorteo', primary_key=True, serialize=False)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('tipo_residente_propietario', models.BooleanField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('hora_sorteo', models.TimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sorteo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoArchivo',
            fields=[
                ('id_tipo_archivo', models.AutoField(db_column='id_tipo_archivo', primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('SOAT', 'SOAT'), ('Tarjeta de propiedad', 'Tarjeta de propiedad'), ('Técnico-mecánica', 'Técnico-mecánica'), ('Licencia', 'Licencia'), ('Identidad', 'Identidad')], max_length=50)),
            ],
            options={
                'db_table': 'tipo_archivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(choices=[('CC', 'CC'), ('CE', 'CE'), ('TI', 'TI'), ('Pasaporte', 'Pasaporte')], max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=13)),
                ('celular', models.CharField(max_length=13)),
                ('estado', models.CharField(default='Activo', max_length=10)),
                ('contraseña', models.CharField(blank=True, max_length=250, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('reset_token_expira', models.DateTimeField(blank=True, null=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.rol')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id_visitante', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
                ('tipo_vehiculo', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=10)),
                ('torre', models.CharField(blank=True, max_length=10, null=True)),
                ('apartamento', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'visitante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaComun',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_zona', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField()),
                ('tipo_pago', models.CharField(choices=[('Por hora', 'Por hora'), ('Franja horaria', 'Franja horaria'), ('Evento', 'Evento')], max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('tarifa_base', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'zona_comun',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehiculoResidente',
            fields=[
                ('id_vehiculo_residente', models.AutoField(db_column='id_vehiculo_residente', primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('tipo_vehiculo', models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], max_length=10)),
                ('activo', models.BooleanField()),
                ('documentos', models.BooleanField(default=False)),
                ('cod_usuario', models.ForeignKey(db_column='cod_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'db_table': 'vehiculo_residente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('Rechazada', 'Rechazada'), ('Aprobada', 'Aprobada'), ('En espera', 'En espera')], default='En espera', max_length=15)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_uso', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('forma_pago', models.CharField(blank=True, choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], max_length=20, null=True)),
                ('valor_pago', models.FloatField(blank=True, null=True)),
                ('cod_usuario', models.ForeignKey(db_column='cod_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
                ('cod_zona', models.ForeignKey(db_column='cod_zona', on_delete=django.db.models.deletion.CASCADE, to='usuario.zonacomun')),
            ],
            options={
                'db_table': 'reserva',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegistroCorrespondencia',
            fields=[
                ('id_correspondencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Recibo', 'Recibo')], max_length=10)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField()),
                ('cod_vigilante', models.ForeignKey(db_column='cod_vigilante', on_delete=django.db.models.deletion.DO_NOTHING, related_name='correspondencias_vigilante', to='usuario.usuario')),
            ],
            options={
                'db_table': 'registro_correspondencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagosReserva',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('archivo_1', models.FileField(upload_to='pagos/')),
                ('archivo_2', models.FileField(blank=True, null=True, upload_to='pagos/')),
                ('estado', models.BooleanField(default=False)),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, to='usuario.reserva')),
            ],
            options={
                'db_table': 'pagos_reserva',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id_novedad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('foto', models.FileField(blank=True, null=True, upload_to='novedades/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_detalle_residente', models.ForeignKey(blank=True, db_column='id_detalle_residente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.detalleresidente')),
                ('id_visitante', models.ForeignKey(blank=True, db_column='id_visitante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.visitante')),
            ],
            options={
                'db_table': 'novedades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('cod_usuario', models.ForeignKey(db_column='cod_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'db_table': 'noticias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GanadorSorteo',
            fields=[
                ('id_ganador', models.AutoField(db_column='id_ganador', primary_key=True, serialize=False)),
                ('fecha_ganado', models.DateTimeField(auto_now_add=True)),
                ('id_detalle_residente', models.ForeignKey(db_column='id_detalle_residente', on_delete=django.db.models.deletion.CASCADE, to='usuario.detalleresidente')),
                ('id_parqueadero', models.ForeignKey(db_column='id_parqueadero', on_delete=django.db.models.deletion.CASCADE, to='usuario.parqueadero')),
                ('id_sorteo', models.ForeignKey(db_column='id_sorteo', on_delete=django.db.models.deletion.CASCADE, to='usuario.sorteo')),
            ],
            options={
                'db_table': 'ganador_sorteo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EntregaCorrespondencia',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('id_correspondencia', models.ForeignKey(db_column='id_correspondencia', on_delete=django.db.models.deletion.DO_NOTHING, related_name='entregas_correspondencia', to='usuario.registrocorrespondencia')),
                ('id_detalle_residente', models.ForeignKey(db_column='id_detalle_residente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='entregas_residente', to='usuario.detalleresidente')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='entregas_usuario', to='usuario.usuario')),
            ],
            options={
                'db_table': 'entrega_correspondencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallesParqueadero',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_propietario', models.CharField(choices=[('Visitante', 'Visitante'), ('Residente', 'Residente')], max_length=10)),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('pago', models.FloatField(blank=True, null=True)),
                ('id_parqueadero', models.ForeignKey(db_column='id_parqueadero', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.parqueadero')),
                ('id_vehiculo_residente', models.ForeignKey(blank=True, db_column='id_vehiculo_residente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.vehiculoresidente')),
                ('id_visitante', models.ForeignKey(blank=True, db_column='id_visitante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.visitante')),
            ],
            options={
                'db_table': 'detalles_parqueadero',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='detalleresidente',
            name='cod_usuario',
            field=models.ForeignKey(db_column='cod_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.CreateModel(
            name='ArchivoVehiculo',
            fields=[
                ('id_archivo', models.AutoField(db_column='id_archivo', primary_key=True, serialize=False)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('id_tipo_archivo', models.ForeignKey(db_column='id_tipo_archivo', on_delete=django.db.models.deletion.CASCADE, to='usuario.tipoarchivo')),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='usuario.vehiculoresidente')),
            ],
            options={
                'db_table': 'archivo_vehiculo',
                'managed': True,
            },
        ),
    ]
