# Generated by Django 4.2.24 on 2025-11-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.AutoField(db_column='ID_paquete', primary_key=True, serialize=False)),
                ('apartamento', models.IntegerField(db_column='apartamento')),
                ('torre', models.IntegerField(db_column='torre')),
                ('fecha_recepcion', models.DateTimeField(db_column='fecha_recepcion')),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=255, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, db_column='fecha_entrega', null=True)),
                ('nombre_residente', models.CharField(blank=True, db_column='nombre_residente', max_length=100, null=True)),
                ('foto_cedula', models.ImageField(blank=True, db_column='foto_cedula', null=True, upload_to='cedulas_entrega/')),
            ],
            options={
                'db_table': 'Paquete',
                'managed': False,
            },
        ),
    ]
