# Generated by Django 4.2.24 on 2025-11-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigilante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paquete',
            options={'managed': False},
        ),
    ]
